name: Release Alpha

on:
  push:
    tags:
      - "v*-alpha.*"

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-node@v7
        with:
          node-version: 24.11.0
          cache: npm
          registry-url: https://registry.npmjs.org

      - run: npm ci
      - run: npm run check
      - run: npm test
      - run: npm run build:all
      - run: npm publish --tag alpha --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: npm publish --workspace=create-electron-vite-plus --tag alpha --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
